
// its not about swith developement but about swith certification
The examination of standards and regulations for #glspl("swith") offers meaningful insights into the challenges of implementing innovative aerospace technologies. The foundational role of standards in emerging technologies became evident through this research, revealing both opportunities and limitations in current regulatory frameworks.

A central finding from the standards investigation in @chap_1_0 is the absence of specific certification procedures for #glspl("swith"). This gap significantly limits both industrial and scientific implementation of the technology. While established standards from related fields offer guidance, they fall short in addressing the distinctive challenges posed by integrating high-pressure hydrogen storage with aircraft structural elements. This observation reflects a broader pattern in technological innovation, where existing frameworks must evolve to accommodate novel engineering approaches.

The interplay of standardization and technological advancement in #gls("swith") development highlights benefits beyond regulatory compliance. While standards traditionally focus on safety and certification requirements, their implementation in #gls("swith") certification serves a broader purpose. 
Standards facilitate knowledge transfer between different domains of expertise. The development of #glspl("swith") draws upon knowledge from various technical fields, including, among others, aerospace engineering, hydrogen storage systems, structural design, and pressure vessel technology. 
Standards from each field help bridge these distinct technical areas, allowing specialists to understand requirements and constraints from other domains. This cross-disciplinary understanding proves crucial when addressing complex challenges, such as integrating high-pressure hydrogen storage systems with primary aircraft structures while maintaining structural integrity and safety requirements.

// ---------------------------- 1_Aero_Standards ---------------------------- //
The investigation of existing aviation standards, particularly #gls("cs")-23 and #gls("cs")-25, revealed significant limitations in their applicability to #glspl("swith"). 
While #gls("cs")-25 includes provisions for pressurized systems through its oxygen equipment requirements, the prescribed test factors and burst factors may prove insufficient for #gls("swith") applications. The substantially higher operating pressures and larger dimensions of hydrogen tanks compared to oxygen systems present compelling arguments against direct application of these standards.

Regional considerations emerge as a significant factor in #gls("swith") standardization, with European standards serving as the primary focus due to the geographical context of this research. While differences exist between European and US standards, their substantial overlap in many areas suggests potential for harmonized approaches to #gls("swith") certification. This alignment extends to document structure and paragraph numbering, indicating established coordination between regulatory bodies.

A systematic review of all available #gls("cs") standards revealed that none can adequately address the certification requirements for #glspl("swith"). 
While these standards provide graduated requirements for different aircraft categories, from the less demanding #gls("cs")-23 to the more comprehensive #gls("cs")-25, they lack provisions for high-pressure hydrogen storage integration with primary aircraft structures.

The timeline of standards development adds another layer of complexity. The announcement of specific hydrogen aviation standards by SAE International, particularly SAE AS 6679 @SAE_Liquid and SAE AS 7373 @@SAE_Gas, demonstrates industry recognition of this regulatory gap. However, the extended development period of these standards, spanning multiple years without completion, underscores the complexity of adapting existing aerospace knowledge to hydrogen systems. This prolonged development suggests that even established space standards, such as ANSI/AIAA S-081B-2018 @ansi_standard_2018, cannot be directly transferred to aviation applications without substantial modification.

The development timeline of new standards provides valuable insights into the complexity of regulating innovative technologies. The five-year span between the publication of space systems standard ANSI/AIAA S-081B-2018 and the ongoing development of aviation hydrogen standards indicates noteworthy differences between space and aviation requirements. 
Time emerged as a crucial factor in standardization for emerging technologies. 

As #glspl("swith") advance from conceptual designs to prototypes and eventually commercial products, regulatory frameworks must adapt accordingly. This insight points to the importance of creating flexible standards that support technological progress while upholding safety requirements.

// --------------------------- 2_Pressure_Vessels --------------------------- //
The examination of pressure vessel technologies for #glspl("swith") exemplifies the intricate relationship between established engineering solutions and innovative aerospace applications. The progression from Type I to Type V tanks demonstrates how technological evolution can both enable and constrain novel implementations. While Type V tanks offer compelling advantages in weight reduction and pressure capacity, their limited commercial maturity highlights a fundamental challenge in aerospace innovation: balancing theoretical benefits against practical implementation requirements.
The decision to recommend Type IV tanks for current #gls("swith") applications stems from a broader understanding of technology readiness in aerospace applications. 
This recommendation particularly resonates with findings from the standards investigation in @chap_1_0, where the absence of specific certification procedures for #glspl("swith") necessitates building upon established technologies. 
The selection of Type IV tanks provides a foundation of proven reliability while supporting the innovative aspects of #gls("swith") development.

The non-linear relationships observed between pressure, storage capacity, and manufacturing costs in pressure vessel development hold significant implications for #glspl("swith"). 
These relationships, demonstrated through experimental data from automotive applications, suggest that optimizing #gls("swith") designs will require more nuanced approaches than simply maximizing pressure capacity. 
This insight connects with the structural considerations detailed in Chapter 2, where the interaction between pressure loads and aircraft structural requirements demands sophisticated design solutions.

The automotive industry's extensive experience with Type IV tanks offers valuable insights for #gls("swith") development, though direct translation of these solutions to aerospace applications requires consideration of additional factors. 
The success of Type IV tanks in vehicles like the Hyundai NEXO and Toyota MIRAI II demonstrates their commercial viability, yet the unique demands of aerospace applications, as explored in Chapter 3's load case assessment, introduce additional complexities. The structural testing optimization framework presented in Chapter 4 will play a crucial role in validating these adaptations for aerospace use.

The evolution of pressure vessel technology suggests a pathway for future #gls("swith") development. As Type V tanks mature and overcome current limitations, their integration into #glspl("swith") could enable significant performance improvements. However, this transition must be guided by comprehensive testing and certification procedures, building upon the frameworks established in Chapter 4. This progression illustrates how technological advancement in one domain can eventually enable innovations in others, provided proper validation and certification processes are established.

Looking beyond individual pressure vessel types, this investigation reveals broader patterns in aerospace innovation. The interaction between material science, structural engineering, and safety requirements demonstrated in pressure vessel development mirrors challenges encountered across other aspects of #gls("swith") design. These parallels suggest that solutions developed for pressure vessel certification might inform approaches to other technical and regulatory challenges in #gls("swith") implementation.