
words_2_find = [
        "crucial",
        "critical",
        "important",
        "significant",
        "substantial",
        "exhibit",
        "provide",
        "obtain",
        "present",
        "method",
        "mention",
        "consider",
        "comprehensive",
        "limitation",
        "configuration",
        "approach",
        "notable",
        "exhaustive",
        "necessitates",
        "necessary",
        "requires",
        "demonstrate",
        "particular",
        "careful",
        "warrant",
        "analy",
        "complexities",
        "fundamental",
        "aspect",
        "systematic",
        "demand",
        
        
        
        "examine",
        "explore", 
        "examine", 
        "addres", 
        "detail",
        "outline",
        "give",
        "factor",
        "profound",
        "implement",
        "vital",
        "technique",
        "potential"
        
        
]