
words_2_find = [
        "crucial",
        "critical",
        "important",
        "significant",
        "substantial",
        "exhibit",
        "provide",
        "obtain",
        "present",
        "method",
        "mention",
        "consider",
        "comprehensive",
        "limitation",
        "configuration",
        "approach",
        "notable",
        "exhaustive",
        "essential",
        "demonstrate",
        "particular",
        "careful",
        "warrant",
        "analy",
        "complexities",
        "fundamental",
        "aspect",
        "systematic",
        "demand",
        
        "work",
        "thesis",
        "challenge",
        
        
        
        "examin", # e, ing,
        "examination",
        "investigation",
        
        "explore", 
        "addres", 
        "detail",
        "outline",
        "give",
        "factor",
        "profound",
        "implement",
        "vital",
        "technique",
        "potential"
        "offer",
        "include",
        "encompas",
        
        "applicable",
        "hurdle",
        "obstacle",
        "barrier",
        "difficult",
        "thorough",
        "framework",
        "evaluate",
        "depict",
        "illustrat",
        "show",
        "state",
        "furthermore",
        "moreover",
        "consequently",
        "however",
        "serve as",
        "establish",
        "act as",
        "listed",
        "appear",
        "specifically",
        "result",
        "represent",
        "denote",
        "stand for",
        "stands for",
        "require",
        "necess" # "necessitate, necessity, necessary"
        "study",
        "major",
        "solution",
        "assess",
        "nevertheless",
        "in addition",
        "cause",
        "lead to",
        "lead",
        "outcome",
        "finding"
        
        
        
]